### ISSUE TITLE
Add publishing support for the "big 3" container registries

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#58]
@reset commented on [Wed Oct 11 2017](https://github.com/habitat-sh/habitat/issues/3742)

Now that we've got the Docker exporter tied into Builder and publishing to the Docker Hub working it's time to add the other major container registries. This should largely be UI focused with the remainder of the work being in validating credentials which may need to be done server side depending upon each provider's CORS support.

- [x] Amazon Container Registry - #3743
- [ ] Google Container Registry - #3745
- [x] Azure Container Registry - #3744 

### To-Do's
- [x] UX: Mockups/Prototype for *Integrations* tab w/multiple registry accounts
- [x] UX: Mockups/Prototype for *Connect a plan file* enable publishing w/multiple registries
- [ ] Define form fields (repo and tag format) for each account type (Docker, GCP, Azure, Amazon) 
- [x] UI: Add new buttons to Integrations tab
- [ ] UI: Update help text below label/heading and on delete confirm dialog
- [ ] UI: Display list of accounts on 'Connect a plan file' step 2 when publishing is turned 'ON'
- [ ] UI: Clicking 'configure this account' opens dialog with form (publish settings)
- [ ] UI: After configured, the 'stop sync' icon would disabled publishing for that account (i.e. remove settings; back to original state of 'configure this account')
- [ ] UI: After configured, the 'gear' icon would re-open the dialog with form pre-filled so user can edit settings.
- [ ] UI: Switching publishing to OFF hides the list of accounts and disabled all publishing
- [ ] Credentials verification

### UI Mockups
1. [Prototype for Integrations tab w/multiple registry accounts](https://chef.invisionapp.com/share/5YDV6902R#/251489938_my_Origins_Integrations)
2. [Prototype - publish to multiple registries](https://chef.invisionapp.com/share/M3E0268WQ#/258859130_package_Detail_V2_-_Settings_Connect_Step_2_Multi_Registries)

---

@ryankeairns commented on [Mon Oct 16 2017](https://github.com/habitat-sh/habitat/issues/3742#issuecomment-337010758)

@reset would users need the ability to export and publish to multiple of these per package? 
In other words, when I connect a plan file to builder, could I enable Docker and Amazon, for example?

cc: @elliott-davis 

---

@elliott-davis commented on [Mon Oct 16 2017](https://github.com/habitat-sh/habitat/issues/3742#issuecomment-337015203)

Also, do I have the ability to support multiple regions of each of these registries?

cc: @ryankeairns 

---

@tashimi commented on [Mon Oct 16 2017](https://github.com/habitat-sh/habitat/issues/3742#issuecomment-337016909)

Yes to both 

> On Oct 16, 2017, at 9:48 PM, Elliott Davis <notifications@github.com> wrote:
> 
> Also, do I have the ability to support multiple regions of each of these registries?
> 
> cc: @ryankeairns
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---

@fnichol commented on [Mon Oct 16 2017](https://github.com/habitat-sh/habitat/issues/3742#issuecomment-337018679)

Beat me to it: yes to both 😄 

We designed the "integrations" to be a list so that there could be multiple types (docker hub, ami), and multiple instances of the same type (ami/us-west-2, ami/us-east-1, etc)

---

@ryankeairns commented on [Mon Oct 16 2017](https://github.com/habitat-sh/habitat/issues/3742#issuecomment-337020279)

![tenor-47856026](https://user-images.githubusercontent.com/446285/31632564-07b84f0e-b283-11e7-8f4b-9c2e2dffee45.gif)

---

@ryankeairns commented on [Tue Oct 17 2017](https://github.com/habitat-sh/habitat/issues/3742#issuecomment-337248928)

Prototype link added to issue description for the Integrations tab. Next, working on prototype for the multiple registry targets in the 'connect a plan file' flow.

---

@ryankeairns commented on [Tue Oct 17 2017](https://github.com/habitat-sh/habitat/issues/3742#issuecomment-337348151)

What do you all think of this approach for publishing to multiple registries when connecting a plan file? I've re-used design patterns that exist elsewhere in the app (e.g. the table list and modal dialogs) with thoughts towards varying config settings based upon registry type (e.g. tag fields would change, etc).

When you 'turn on' publishing, you would see a list of all the registry accounts that you've configured on the Origins > Integrations tab. From this list, you could activate/configure as many as desired.

In this mini prototype, you can activate Docker Hub publishing, then remove it.
[Prototype - publish to multiple registries](https://chef.invisionapp.com/share/M3E0268WQ#/258859130_package_Detail_V2_-_Settings_Connect_Step_2_Multi_Registries)

---

@reset commented on [Wed Oct 18 2017](https://github.com/habitat-sh/habitat/issues/3742#issuecomment-337494635)

@ryankeairns I think it looks great - I think it's just fine for now to publish to only one of each type but I think in the future people may want to be able to publish to `n` number of Docker Hub repositories

**Comment by tashimi** [comment]
@elliott-davis do we want to update or close this?

**Comment by elliott-davis** [comment]
Depends, we still need GCR support but there way of publishing packages is
insanely harder. I'd say it's probably safe to close and we can create a
new card for GCR when the time comes.
